class TTVisitor:
  def visit(self, obj: object, *args: object, **kwargs: object) -> None: ...
  def visitAttr(
    self, obj: object, attr: str, value: object, *args: object, **kwargs: object
  ) -> bool | None: ...
